# Generated by Django 5.1.1 on 2024-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('BR', 'BRAZIL'), ('US', 'ESTADOS UNIDOS'), ('CA', 'CANADÁ'), ('CN', 'CHINA'), ('FR', 'FRANÇA'), ('MX', 'MÉXICO'), ('ZA', 'ÁFRICA DO SUL')], max_length=200)),
            ],
        ),
    ]
