# Generated by Django 5.1.1 on 2024-11-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('BRAZIL', 'BRASIL'), ('USA', 'ESTADOS UNIDOS'), ('CA', 'CANADÁ'), ('CN', 'CHINA'), ('FR', 'FRANÇA'), ('MX', 'MÉXICO'), ('ZA', 'ÁFRICA DO SUL')], max_length=200),
        ),
    ]
